# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ken Bellows
email: ken.bellows@live.com
description: > # this means to ignore newlines until "baseurl:"
  These are some thoughts on life, code, politics, philosophy,
  technology, and whatever else happens to be on my mind.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://kenbellows.github.io" # the base hostname & protocol for your site
twitter_username: ken_bellows
github_username: kenbellows

# Build settings
markdown: kramdown
